export const Types = {
    FETCH_POST: 'FETCH_POST',
    FETCH_POST_SUCCESFUL: 'FETCH_POST_SUCCESFUL',
    FETCH_POST_FAIL: 'FETCH_POST_FAIL',

    DELETE_POST: 'DELETE_POST',
    DELETE_POST_SUCCESFUL: 'DELETE_POST_SUCCESFUL',
    DELETE_POST_FAIL: 'DELETE_POST_FAIL'
};